// This file is automatically generated. Do not edit it directly.
// Powered by EnterCloud Managed Supabase
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://spb-t4n0n4c4tj1e1r0t.supabase.opentrust.net";
export const SUPABASE_PUBLISHABLE_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiYW5vbiIsInJlZiI6InNwYi10NG4wbjRjNHRqMWUxcjB0IiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE3ODQ1OTA2NzYsImV4cCI6MjEwMDE2NjY3Nn0.F3w8Cd3eO5_H6Ouurnef2MZsnSO8Ly6kkuSJ1NLBfIU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
